### ISSUE TITLE
Trailing comma in multi-line function invocations raise

### ISSUE THREAD

**Issue by trotterdylan** [m-labs/pyparser#5]
In CPython, the following works:

```
>>> code = """
... def foo(x, y):
...  print x, y
... foo(
...  1,
...  2,
... )
... """
>>> exec code
1 2
```

pythonparser.parse() on the same code causes an exception:

```
>>> pythonparser.parse(code)
<unknown>:7:1-7:2: fatal: unexpected ): expected (, *, **, +, -, [, `, complex, float, ident, int, lambda, not, strbegin, { or ~
)
^
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trotterd/projects/grumpy/build/lib/python2.7/site-packages/pythonparser/__init__.py", line 58, in parse
    mode, flags, version, engine)
  File "/Users/trotterd/projects/grumpy/build/lib/python2.7/site-packages/pythonparser/__init__.py", line 28, in parse_buffer
    return parser.file_input(), lexer.comments
  File "/Users/trotterd/projects/grumpy/build/lib/python2.7/site-packages/pythonparser/parser.py", line 89, in outer_rule
    result = inner_rule(parser)
  File "/Users/trotterd/projects/grumpy/build/lib/python2.7/site-packages/pythonparser/parser.py", line 151, in rule
    parser.diagnostic_engine.process(error)
  File "/Users/trotterd/projects/grumpy/build/lib/python2.7/site-packages/pythonparser/diagnostic.py", line 165, in process
    raise Error(diagnostic)
pythonparser.diagnostic.Error: <unknown>:7:1-7:2: fatal: unexpected ): expected (, *, **, +, -, [, `, complex, float, ident, int, lambda, not, strbegin, { or ~
)
^
```

**Comment by whitequark** [comment]
This actually has nothing to do with multi-line invocations, `f(1,2,)` also fails.
